### PR TITLE
Integrate make to the development process

### PR DESCRIPTION
**Pull request by shackra**
this helps with brevity of the commands one needs to type to make things happen, also, some extra
help text is provided to guide newcomers on what they are expected to do after any execution of make <thing>

### CODE REVIEW

**Comment by ubolonton** [comment]
Can you also change the CI config files to use `make`?

The Windows section in the doc also needs to be expanded, since it will be more different from macOS/Linux than before.

**Comment by shackra** [comment]
well, naturally apt-get will fail on MacOS

**Comment by shackra** [comment]
Okay, I don't understand what went wrong with the tests themselves. Any pointers?

**Comment by ubolonton** [comment]
Seems like the Rust grammar changed, invalidating the test. It’s not related to the changes here. I’ll check it.

**Comment by shackra** [comment]
after that the PR can be merged?

**Pull request merged**
