### PR TITLE
Add csharp highlight query

### PR DESCRIPTION
**Pull request by jcs090218**

### CODE REVIEW

**Comment by theothornhill** [comment]
Should these queries be maintained in two places? Not sure I understand the rationale here. Why not contribute your additions to `csharp-mode`?

**Comment by ubolonton** [comment]
The queries bundled by `tree-sitter-langs` are for packages that are not `tree-sitter`-aware. `csharp-mode` is, so queries contributions for C# should go there.

**Comment by jcs090218** [comment]
Got it! Thanks!

**Comment by jcs090218** [comment]
@ubolonton I got one question here. Do you mean `csharp-mode` or `csharp-tree-sitter-mode`? `csharp-mode` doesn't aware of `tree-sitter`, but only `csharp-tree-sitter-mode` does (they both are major mode).

**Comment by ubolonton** [comment]
I mean the package, not the individual major modes.

**Pull request closed without merging**
